name: Killer Web Front - Test
on: [push]
env:
  FRONT_URL: ${{ secrets.FRONT_URL }}
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Installs pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - run: echo "🎉 ${{ github.event_name }} event on ${{ github.ref }} triggered this action."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server."

      - name: Copy Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Type checking
        run: pnpm tsc

      - name: Lint code
        run: pnpm lint

      - name: Unit test code
        run: pnpm test

      - name: Build Web Front
        run: pnpm build
