name: Testing
on:
  push:
    branches: [main]
    paths-ignore:
      - 'apps/mobile/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'apps/mobile/**'
env:
  FRONT_URL: ${{ secrets.FRONT_URL }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installs pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Type checking
        run: pnpm tsc

      - name: Lint code
        run: pnpm lint

      - name: Unit test code
        run: pnpm test
